services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
