spring:
  application:
    name: car-service
  data:
    mongodb:
      uri: mongodb+srv://lorenzopaolucci:pcto-project@cluster0.dfni7.mongodb.net/pcto?retryWrites=true&w=majority
    mongo:
      repositories:
        enabled: true

